### ISSUE TITLE
don't know what happened

### ISSUE THREAD

**Issue by sebphfx** [m-ryan/magic_encoding#4]
but I use magic_encoding in a Gems folder and it copied a part of the end of every file. So now I m stuck with 1798 files with crap at the bottom. I don't know If I can use magic_encoding to remove these lines but I ll have to use Regex I guess. Not funny at all. I wish there was more documentation even if it's easy to use.

edit: ok. i freaked out for nothing. I didnt know it literally takes 5 minutes to uninstall and reinstall all your gems.I don't know what happened. Magic_encoding is great but at first I entered "magic_encoding /path/to/folder/ not realizing there should be an option or flag in it's place.

**Comment by plucb** [comment]
Even with the flag between the path and magic_encoding, it does the same thing as it did for you... it copy the last line of every file to be encoded.

Does it happens to anyone else?
